// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADr9OULmPMxClDdBc842MQZ48l7mmjzFs',
    appId: '1:481770706092:web:2015f012413f987ac63b09',
    messagingSenderId: '481770706092',
    projectId: 'sih-2025-38404',
    authDomain: 'sih-2025-38404.firebaseapp.com',
    storageBucket: 'sih-2025-38404.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7M7M0-Bysq5VsZ5BnjHc5uQ2LyIvXVWE',
    appId: '1:481770706092:android:bf7dc69dce048c47c63b09',
    messagingSenderId: '481770706092',
    projectId: 'sih-2025-38404',
    storageBucket: 'sih-2025-38404.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBecfigPrLfZqctqc0nuCZio1ac_pTaB1M',
    appId: '1:481770706092:ios:701fcd54166d1032c63b09',
    messagingSenderId: '481770706092',
    projectId: 'sih-2025-38404',
    storageBucket: 'sih-2025-38404.firebasestorage.app',
    iosBundleId: 'com.example.sih25044',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBecfigPrLfZqctqc0nuCZio1ac_pTaB1M',
    appId: '1:481770706092:ios:701fcd54166d1032c63b09',
    messagingSenderId: '481770706092',
    projectId: 'sih-2025-38404',
    storageBucket: 'sih-2025-38404.firebasestorage.app',
    iosBundleId: 'com.example.sih25044',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADr9OULmPMxClDdBc842MQZ48l7mmjzFs',
    appId: '1:481770706092:web:d59471ceaa6552c9c63b09',
    messagingSenderId: '481770706092',
    projectId: 'sih-2025-38404',
    authDomain: 'sih-2025-38404.firebaseapp.com',
    storageBucket: 'sih-2025-38404.firebasestorage.app',
  );

}