// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQxNt5wVW1GWI21aCIZVM39cMGx6ShZ8o',
    appId: '1:131474395134:web:31c7d7ae2f2bf2db6fbaaf',
    messagingSenderId: '131474395134',
    projectId: 'sih-25044',
    authDomain: 'sih-25044.firebaseapp.com',
    storageBucket: 'sih-25044.firebasestorage.app',
    measurementId: 'G-3870HQ79VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjFfY4ekwvqVgsjAbcuJfsk_lvqxEhqaQ',
    appId: '1:131474395134:android:db3616950dd8b5fe6fbaaf',
    messagingSenderId: '131474395134',
    projectId: 'sih-25044',
    storageBucket: 'sih-25044.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb0DYgqn0ij5onvKSC6wsjat1K-RTtzPs',
    appId: '1:131474395134:ios:4df1d11bc0cc58de6fbaaf',
    messagingSenderId: '131474395134',
    projectId: 'sih-25044',
    storageBucket: 'sih-25044.firebasestorage.app',
    iosBundleId: 'com.example.sih25044',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb0DYgqn0ij5onvKSC6wsjat1K-RTtzPs',
    appId: '1:131474395134:ios:4df1d11bc0cc58de6fbaaf',
    messagingSenderId: '131474395134',
    projectId: 'sih-25044',
    storageBucket: 'sih-25044.firebasestorage.app',
    iosBundleId: 'com.example.sih25044',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQxNt5wVW1GWI21aCIZVM39cMGx6ShZ8o',
    appId: '1:131474395134:web:c66cd7b8aa0399a56fbaaf',
    messagingSenderId: '131474395134',
    projectId: 'sih-25044',
    authDomain: 'sih-25044.firebaseapp.com',
    storageBucket: 'sih-25044.firebasestorage.app',
    measurementId: 'G-0RHVW7RT7N',
  );
}
